AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an Amazon Route 53 hosted zone
Parameters:
  RootDomainName:
    Type: String
    Description: The DNS name of an Amazon Route 53 hosted zone e.g. mysite.io
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
Resources:
  DNS:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join ['', ['Hosted zone for ', !Ref 'RootDomainName']]
      Name: !Ref 'RootDomainName'
      HostedZoneTags:
      - Key: Application
        Value: Blog
