spring:
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect